### ISSUE TITLE
(feat): adjust for different terminal window sizes

### ISSUE THREAD

**Issue by lrsvmb** [Jojo4GH/nav#2]
Currently, nav does not scale its upper list limit to match the current terminal height. This results in scenarios like this, where you need to blindly navigate a few entries to swap to the bottom:

https://github.com/user-attachments/assets/1c22ffb0-b8ee-4178-8784-ce67810ebd75

It would be great for nav to adjust its list "height" to the window size given :partying_face:

**Comment by Jojo4GH** [comment]
Will be included in the next release 👍🏻
